include:
  - ./compose.db-env.yml

services:
  backend:
    build:
      args:
        BACKEND_HOST: ${BACKEND_HOST:-0.0.0.0}
        BACKEND_HOST_PORT: ${BACKEND_HOST_PORT:-80}
      context: ./../
      dockerfile: ./.docker/Dockerfile
      target: prod
    container_name: backend
    develop:
      watch:
        - action: sync
          path: ./../app/
          target: /app/app
        - action: rebuild
          path: ./../pyproject.toml
          target: /app/pyproject.toml
    env_file:
      - ./.application.env
    environment:
      BACKEND_HOST: ${BACKEND_HOST:-0.0.0.0}
      BACKEND_HOST_PORT: ${BACKEND_HOST_PORT:-80}
      POSTGRES_CONTAINER_NAME: db
      POSTGRES_HOST: ${POSTGRES_CONTAINER_NAME:-db}
      POSTGRES_DB: ${POSTGRES_DB:-geomaniac}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    networks:
      - backend-net
