name: lint

on:
  push:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ./.venv/
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: create .venv
        run: python3 -m venv .venv

      - name: install poetry
        run: . ./.venv/bin/activate && pip install poetry

      - name: install deps
        run: . ./.venv/bin/activate && poetry install --no-root

      - name: lint
        run: . ./.venv/bin/activate && . ./.scripts/lint.sh
